# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Homepage of the Research Group Molecular Systems Evolution
email: dutheil(at)evolbio.mpg.de
description: >- # this means to ignore newlines until "baseurl:"
  The Molecular Systems Evolution research group studies molecular evolution at distinct organizational levels. Its central goal is understanding the interaction between stochastic processes and natural selection. Our research questions are articulated around three major axes: (1) modelling the genealogical process of neutral sequence evolution to infer the history of populations, (2) characterising adaptive processes in time and along genomes, with a focus on the role of epistatic interactions, and (3) studying the evolution of the so-called expression noise and its contribution to regulatory networks evolution. The first axis relies on population genetic modelling, specifically coalescence theory, and hidden Markov chains to design new population genomics inference tools. The second axis builds on fitness landscapes theory, population genetics, and structural biology. The third axis is a new venture in the realm of evolutionary single-cell biology, for which we developed new statistical models and designed experimental protocols to generate new comparative datasets.
baseurl: ""
url: "https://molsysevol.github.io"
  #twitter_username: jekyllrb
  #github_username:  jekyll

# Build settings
#theme: minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
    
remote_theme: 
  rohanchandra/type-theme
  #aterenin/minima-reboot


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Homepage of the Research Group Molecular Systems Evolution
  avatar: assets/img/logo.png
  favicon: 
  gravatar: # Email MD5 hash
  description: "Homepage of the Research Group Molecular Systems Evolution" # used by search engines
  # Header and footer text
  header_text: >
     The Molecular Systems Evolution research group studies molecular evolution at distinct organizational levels. Its central goal is understanding the interaction between stochastic processes and natural selection. Our research questions are articulated around three major axes: (1) modelling the genealogical process of neutral sequence evolution to infer the history of populations, (2) characterising adaptive processes in time and along genomes, with a focus on the role of epistatic interactions, and (3) studying the evolution of the so-called expression noise and its contribution to regulatory networks evolution. The first axis relies on population genetic modelling, specifically coalescence theory, and hidden Markov chains to design new population genomics inference tools. The second axis builds on fitness landscapes theory, population genetics, and structural biology. The third axis is a new venture in the realm of evolutionary single-cell biology, for which we developed new statistical models and designed experimental protocols to generate new comparative datasets.
  header_text_feature_image: assets/img/board_banner_1.png
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>
  site_navigation_sort: order

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."


# PAGINATION
paginate: 5
paginate_path: "news/page:num"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
